TERMINALS = {
    "TERMINATOR": 0,
    "QUANTIFIER": 0,
    "CHARSET_ESCAPE": 0,
    "SYMBOL": 0,
    "LEFT_SQUARE_BRACKET": '[',
    "RIGHT_SQUARE_BRACKET": ']',
    "LEFT_PARENTHESIS": '(',
    "RIGHT_PARENTHESIS": ')',
    "COMMA": ',',
    "MINUS": '-',
    "INVERSE": '^',
    "SPLIT": '|',
    "EXCLAIMA": '!',
    "ASSIGNER": "=",
    "SEMICOLON": ";",
}
