TERMINALS = {
    "AT": "@",
    "DOT": ".",
    "PTR": "->",
    "COMMA": ",",
    "COLON": ":",
    "CONCAT": "`",
    "HASHTAG": "#",
    "SEMICOLON": ";",
    "QUESTION_MARK": "?",
    "LEFT_PAREN": "(",
    "RIGHT_PAREN": ")",
    "LEFT_BRACKET": "{",
    "RIGHT_BRACKET": "}",
    "LEFT_SQUARE_BRACKET": "[",
    "RIGHT_SQUARE_BRACKET": "]",
    "ASSIGN": "=",

    "ATTRIBUTE": "attribute",
    "UNDEFINE": "undefine",
    "INCLUDE": "include",
    "IMPORT": "import",
    "MACRO": "macro",
    "RAISE": "raise",
    "FROM": "from",
    "LET": "let",

    "IF": "if",
    "ELSE": "else",
    "DO": "do",
    "FOR": "for",
    "WHILE": "while",
    "CASE": "case",
    "SWITCH": "switch",
    "DEFAULT": "default",
    "BREAK": "break",
    "CONTINUE": "continue",
    "RETURN": "return",
    "WITH": "with",
    "ENUM": "enum",
    "TYPEOF": "typeof",
    "VAR": "var",

    "BOOL_BIN_OP": 0,
    "BOOL_SIN_OP": 0,
    "COND_BIN_OP": 0,
    "COND_SIN_OP": 0,
    "ARITH_0_BIN_OP": 0,
    "ARITH_0_SIN_OP": 0,
    "ARITH_1_BIN_OP": 0,
    "ARITH_1_SIN_OP": 0,
    "ARITH_2_BIN_OP": 0,
    "ARITH_2_SIN_OP": 0,
    "ARITH_3_BIN_OP": 0,
    "ARITH_3_SIN_OP": 0,

    "CHARACTER_LITERAL": 0,
    "STRING_LITERAL": 0,
    "IDENTIFIER": 0,
    "TERMINATOR": 0,
    "PREFIX": 0,
    "NUMBER": 0,
    "TOKEN": 0,
    "PATH": 0,
}
