TERMINALS = {
    "TERMINATOR": 0,
    "BEGIN_CHARSET": '[',
    "BEGIN_GROUP": '(',
    "BEGIN_QUANTIFIER": '{',
    "CHAR": 0,
    "COMMA": ',',
    "END_CHARSET": ']',
    "END_GROUP": ')',
    "END_QUANTIFIER": '}',
    "MINUS": '-',
    "NOT": '^',
    "NUMBER": 0,
    "SPLIT": '|',
    "PLUS": '+',
    "QUEST": '?',
    "ASSERT": '!',
    "TIMES": '*',
    "SET_ESCAPE": 0,
}
