"""
* License
*
* XNFjson2C - convert json generated by xnf to C source file
* Copyright (C) 2024 Yaokai Liu
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <https://www.gnu.org/licenses/>.
*
* Project Name: XNFjson2C
* Module Name:
* Filename: Generator.py
* Creator: Yaokai Liu
* Create Date: 2025-5-3
* Copyright (c) 2025 Yaokai Liu. All rights reserved.
"""
import os.path
from pathlib import Path
import json
from string import Template as Tp
from DATA import *
import re
from functools import cmp_to_key as c2k


class Rule:
    def __init__(self, name, generator):
        self.name = name
        target, items = generator.rules[name].split('->')
        self.target = target.strip()
        if self.target == '~':
            self.target = generator.GRAMMAR_TARGET
        items = items.strip()
        if len(items) > 0:
            self.items = items.split(' ')
        else:
            self.items = []


class Action:
    def __init__(self, p, generator):
        rule_prefix = generator.rule_prefix or generator.prefix
        state_prefix = generator.state_prefix or generator.prefix
        token_prefix = generator.token_prefix or generator.prefix

        if not p.startswith('('):
            rule = Rule(p, generator)
            self.action = f"{generator.prefix}_action_reduce"
            self.type = f"{token_prefix}_TOKEN_{rule.target}"
            self.count = len(rule.items)
            self.offset = f"{rule_prefix}_RULE_{p}" if p != "__EXTEND_RULE__" else f"{rule_prefix}_RULE_{rule.target}_EXT"
        else:
            self.action = f"{generator.prefix}_action_stack"
            self.type = 0
            self.count = 0
            self.offset = f"{generator.state_to_enum(p)[0]}"

    def __eq__(self, other):
        return self.action == other.action \
            and self.type == other.type    \
            and self.count == other.count  \
            and self.offset == other.offset

    def to_string(self):
        return ("{"
                f".action = {self.action},"
                f".type = {self.type},"
                f".count = {self.count},"
                f".offset = {self.offset},"
                "}")


class Generator:
    def __init__(self, json_dir: Path | str, template_dir: Path | str, out_dir: Path | str, target: str):
        self.JSON_DIR = Path(json_dir)
        self.TEMPLATE_DIR = Path(template_dir)
        self.OUT_DIR = Path(out_dir)
        self.GRAMMAR_TARGET = target
        self.license = None

        self.__tokens = self.get_json_from("tokens.json")
        self.terminals = [self.format(t) for t in sorted(self.__tokens['terminal'])]
        self.targets = self.__tokens['non-terminal']
        self.targets.remove("~")
        self.targets = sorted(self.targets)
        self.tokens = sorted(self.terminals + self.targets)
        if os.path.isfile(self.JSON_DIR / "automaton-compact.json"):
            self.table = self.get_json_from("automaton-compact.json")
        else:
            self.table = self.get_json_from("automaton.json")
        for val in self.table.values():
            if '$' in val.keys(): val['TERMINATOR'] = val.pop('$')
        self.rules = self.get_json_from("rules.json")
        self.status, self.reflect = dict(), dict()
        for s, p in enumerate(self.table.keys()):
            self.status[s], self.reflect[p] = self.table[p], s
        self.extend_tokens = self.tokens
        self.context = "void"
        self.state_prefix = ""
        self.token_prefix = ""
        self.rule_prefix = ""
        self.prefix = ""
        self.types = dict()


    def set_license(self, _license: str):
        self.license = _license
    def set_extend_tokens(self, tokens):
        self.extend_tokens = tokens

    def set_context(self, context: str):
        self.context = context

    def set_prefix(self, prefix: str):
        self.prefix = prefix

    def set_state_prefix(self, prefix: str):
        self.state_prefix = prefix

    def set_rule_prefix(self, prefix: str):
        self.rule_prefix = prefix

    def set_token_prefix(self, prefix: str):
        self.token_prefix = prefix

    def set_types(self, types: dict):
        self.types = types

    @classmethod
    def format(cls, token: str):
        return "TERMINATOR" if token == "$" else token

    def get_json_from(self, filename: str):
        with open(self.JSON_DIR / filename, 'r') as fp:
            return json.load(fp)

    def get_temp_from(self, filename: str):
        with open(self.TEMPLATE_DIR / filename, 'r') as fp:
            return fp.read()
    def rule_to_name(self, rule: str):
        rule_prefix = self.rule_prefix or self.prefix
        if rule == '__EXTEND_RULE__':
            return f'{rule_prefix}_{self.GRAMMAR_TARGET}_EXT'
        else:
            return f'{rule_prefix}_{rule}'

    def rule_to_enum(self, rule: str):
        rule_prefix = self.rule_prefix or self.prefix
        if rule == '__EXTEND_RULE__':
            return f'{rule_prefix}_RULE_{self.GRAMMAR_TARGET}_EXT'
        else:
            return f'{rule_prefix}_RULE_{rule}'

    def rule_target(self, rule: str):
        target = re.sub(r'_\d+$', '', rule) if rule != '__EXTEND_RULE__' else self.GRAMMAR_TARGET
        return self.types.get(target) or target

    def gen_terminals(self):
        token_prefix = self.token_prefix or self.prefix
        _license = Tp(self.license).substitute(filename="terminal.gen.c")
        template = Tp(self.get_temp_from("terminal.c.tpl"))
        body = ',\n  '.join([f'{token_prefix}_TOKEN_{t}' for t in self.terminals if TERMINALS[t] != 0])
        strings = ',\n  '.join([f'[{token_prefix}_TOKEN_{t}] = string_t("{TERMINALS[t]}")' for t in self.terminals if TERMINALS[t] != 0])
        string_lens = ',\n  '.join([f'[{token_prefix}_TOKEN_{t}] = {len(TERMINALS[t])}' for t in self.terminals if TERMINALS[t] != 0])
        terminals_entry = template.substitute(license=_license, strings=strings, string_lens=string_lens, terminals=body)
        with open(self.OUT_DIR / "terminal.gen.c", 'w') as fp:
            fp.write(terminals_entry)

    def state_to_enum(self, p):
        state_prefix = self.state_prefix or self.prefix
        p = p.strip('()').split(', ')
        _state = '_'.join(p)
        current = 'TERMINATOR' if len(p) == 1 and p[0] == '' else p[-1]
        _state = f'{state_prefix}_state_{_state}' if _state else f'{state_prefix}_state_'
        return _state, current

    def gen_rules(self):
        rule_prefix = self.rule_prefix or self.prefix
        rule_names = self.rules.keys()
        args = f"(Token argv[], {self.context} *, ErrInfo *, const Allocator * allocator)"
        enum_reduces = sorted(f"{self.rule_to_enum(r)} = {i + 1}" for i, r in enumerate(rule_names))
        rules = sorted(f"{self.rule_target(r)} * {self.rule_to_name(r)} {args};" for r in rule_names)
        assign_reduces = sorted([f"[{self.rule_to_enum(r)}] = (fn_{rule_prefix.lower()}_reduce *) {self.rule_to_name(r)}" for r in rule_names])
        template = Tp(self.get_temp_from("rules.h.tpl"))
        _license = Tp(self.license).substitute(filename="rules.gen.h")
        content = template.substitute(
            license=_license,
            enum_reduces=',\n  '.join(enum_reduces),
            reduces='\n'.join(rules)
        )
        with open(self.OUT_DIR / "rules.gen.h", 'w') as fp:
            fp.write(content)
        _license = Tp(self.license).substitute(filename="rules.gen.c")
        content = Tp(self.get_temp_from("rules.c.tpl")).substitute(
            license=_license,
            assign_reduces=',\n  '.join(assign_reduces)
        )
        with open(self.OUT_DIR / "rules.gen.c", 'w') as fp:
            fp.write(content)


    def gen_action_table(self):
        token_prefix = self.token_prefix or self.prefix
        def token_cmp(t1, t2):
            a = self.extend_tokens.index(t1)
            b = self.extend_tokens.index(t2)
            return 1 if a > b else 0 if a == b else -1
        state_enum, states, actions, jumps, units, currents = [], [], [], [], [], []
        for p, q in self.table.items():
            _state, current = self.state_to_enum(p)
            state_enum.append(f'{_state} = {len(state_enum) + 1}')
            _tokens = q.keys()
            _terminals = sorted(_tokens & set(self.terminals), key=c2k(token_cmp))
            _targets = sorted(_tokens & set(self.targets), key=c2k(token_cmp))
            state = {
                "ndx_base": len(actions),
                "goto_base": len(jumps),
                "token_base": len(units),
                "n_tokens": len(_tokens),
            }
            items, ndx, addend = dict(), [], []
            for t in _terminals:
                act = Action(q[t], self)
                if act not in addend:
                    addend.append(act)
                items[t] = addend.index(act)
            actions += [a.to_string() for a in addend]
            for i, t in enumerate(_targets):
                jumps.append(f"{self.state_to_enum(q[t])[0]}")
                items[t] = i
            for i, t in enumerate(sorted(_tokens)):
                ndx.append(str(i))
                units.append(f"{{.type = {token_prefix}_TOKEN_{t}, .offset = {items[t]}}}")
            string = ', '.join([f".{k} = {v}" for k, v in state.items()])
            states.append(f"[{_state}] = {{{string}}}")
            currents.append(f"[{_state}] = {token_prefix}_TOKEN_{current}")

        template = Tp(self.get_temp_from("action-table.c.tpl"))
        _license = Tp(self.license).substitute(filename="action-table.gen.c")
        content = template.substitute(
            license=_license,
            actions=",\n  ".join(actions),
            jumps=",\n  ".join(jumps),
            units=",\n  ".join(units),
            states=",\n  ".join(states),
            currents=",\n  ".join(currents),
        )
        with open(self.OUT_DIR / "action-table.gen.c", 'w') as fp:
            fp.write(content)
        _license = Tp(self.license).substitute(filename="action-table.gen.h")
        content_h = Tp(self.get_temp_from("action-table.h.tpl")).substitute(
            license=_license, state_enum=',\n  '.join(state_enum)
        )
        with open(self.OUT_DIR / "action-table.gen.h", 'w') as fp:
            fp.write(content_h)

    def generate(self):
        self.gen_terminals()
        self.gen_rules()
        self.gen_action_table()

def gen_token_enum(template: Path, _license: str, prefix: str, tokens, out):
    with open(template, 'r') as fp:
        temp = fp.read()
    template = Tp(temp)
    enums = ',\n  '.join([f"{prefix}_TOKEN_{t} = {i + 1}" for i, t in enumerate(tokens)])
    enums += ',\n  ' + f'{prefix}_MAX_REAL_TOKEN = {len(tokens) + 1}'
    enums_entry = template.substitute(license=_license, enums=enums)
    with open(out, 'w') as fp:
        fp.write(enums_entry)
def gen_token_name(template: Path, _license: str, prefix: str, tokens, out):
    with open(template, 'r') as fp:
        temp = fp.read()
    template = Tp(temp)
    names = ',\n  '.join([f'[{prefix}_TOKEN_{t}] = string_t("{t}")' for t in tokens])
    names_entry = template.substitute(license=_license, names=names)
    with open(out, 'w') as fp:
        fp.write(names_entry)
